name: smoke-test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Smoke test
        run: |
          python - <<'PY'
          import transformers, torch, datasets, peft, evaluate
          print("Transformers:", transformers.__version__)
          print("Torch:", torch.__version__)
          print("Datasets:", datasets.__version__)
          print("PEFT:", peft.__version__)
          print("Evaluate:", evaluate.__version__)
          PY
